version: '3.7'

services:
  client:
    container_name: seismic-risc-client
    build:
      context: ./client
    volumes:
      - ./client:/code
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      NODE_ENV: development

  api:
    container_name: seismic-risc-api
    build:
      context: ./api
      args:
        DEVBUILD: 1
    command: ["./manage.py migrate --noinput && ./manage.py runserver 0.0.0.0:8000"]
    volumes:
      - ./api:/code
    ports:
      - "8000:8000"
    environment:
      DJANGO_CONFIGURATION: Dev

volumes:
  pgdata:
